ABC5-TEAM2/From-Busan

src/main/resources/static/css/Info.css
src/main/resources/templates/tourist/TouristSpotInfo.html

[UPDATE] touristInfo수정

---

README.md
src/main/java/com/frombusan/controller/CourseController.java

[TEST] asd

---

src/main/resources/templates/main/index.html

[TEST] test

---

src/main/resources/templates/fragments/header.html
src/main/resources/templates/main/index.html

[UPDATE] index,header수정

---

src/main/java/com/frombusan/controller/CourseController.java
src/main/resources/static/css/Info.css
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/review/list.html
src/main/resources/templates/review/read.html

[UPDATE] festival

---

src/main/java/com/frombusan/controller/MemberController.java
src/main/java/com/frombusan/model/member/MemberUpdateForm.java
src/main/java/com/frombusan/repository/MemberMapper.java
src/main/resources/mapper/memberMapper.xml
src/main/resources/static/css/Info.css
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/member/changePassword.html
src/main/resources/templates/member/findPassword.html
src/main/resources/templates/tourist/TouristSpotInfo.html

명소*축제 상세페이지 수정 & 아이디찾기 & 비밀번호 수정

[UPDATE]fes*tourInfo & FindId*Password

---

src/main/resources/static/css/courseInfo.css
src/main/resources/templates/course/CourseInfo.html

[COURSEISBEST] silkroad

---

src/main/java/com/frombusan/controller/ReviewController.java
src/main/java/com/frombusan/service/ReviewService.java
src/main/resources/static/css/reviewUpdateForm.css
src/main/resources/templates/review/update.html

[UPDATE] reviewupdate(오류있을수도)

---

src/main/java/com/frombusan/controller/CourseController.java

[UPDATE] error해결

---

src/main/java/com/frombusan/controller/MemberController.java
src/main/resources/static/css/myJjimList.css
src/main/resources/static/css/myPage.css
src/main/resources/templates/member/myJjimList.html

[UPDATE] wishpage수정

---

src/main/resources/templates/member/myJjimList.html

[UPDATE] href수정

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/resources/static/css/loginForm.css
src/main/resources/templates/member/findId.html
src/main/resources/templates/member/loginForm.html
src/main/resources/templates/member/myJjimList.html
src/main/resources/templates/member/myReviewList.html
src/main/resources/templates/member/mypage.html
src/main/resources/templates/member/updateMember.html

[RECHECK] findID

---

src/main/resources/static/css/loginForm.css
src/main/resources/templates/member/mypage.html
src/main/resources/templates/member/updateMember.html

[UPDATE]updatemember

---

build.gradle
pom.xml
src/main/java/com/frombusan/config/WebConfig.java
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/tourist/TouristSpotInfo.html

[UPDATE] fes*tourInfo like*Jjim

---

src/main/java/com/frombusan/controller/MemberController.java
src/main/java/com/frombusan/model/member/MemberJoinForm.java
src/main/resources/templates/member/joinForm.html
src/main/resources/templates/member/loginForm.html

joinForm수정

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/review/list.html

리스트html에 대충 버튼 만들어서 번역 되게끔 했씁당~

[UPDATE] list.html translate clear

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/review/list.html
src/main/resources/templates/tourist/TouristSpotInfo.html

[UPDATE] translate

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/FestivalController.java
src/main/java/com/frombusan/controller/HomeController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/festival/FestivalList.html
src/main/resources/templates/review/list.html

[UPDATE] fes-tour translate (도중)

---

src/main/java/com/frombusan/controller/ReviewController.java

Reverts ABC5-TEAM2/From-Busan#40

Revert "[update]"

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/ReviewController.java
src/main/java/com/frombusan/controller/TouristController.java
src/main/resources/static/css/index.css
src/main/resources/templates/member/myJjimList.html
src/main/resources/templates/review/reviewList.html

[UPDATE] error

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/ReviewController.java
src/main/java/com/frombusan/controller/TouristController.java
src/main/resources/static/css/index.css
src/main/resources/templates/member/myJjimList.html
src/main/resources/templates/review/reviewList.html

Reverts ABC5-TEAM2/From-Busan#44

Revert "[UPDATE] error"

---

src/main/java/com/frombusan/controller/ReviewController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/review/read.html

Reverts ABC5-TEAM2/From-Busan#43

Revert "[update] translate"

---

src/main/java/com/frombusan/controller/ReviewController.java

Reverts ABC5-TEAM2/From-Busan#42

Revert "Revert "[update]""

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/FestivalController.java
src/main/java/com/frombusan/controller/HomeController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/festival/FestivalList.html
src/main/resources/templates/review/list.html

Reverts ABC5-TEAM2/From-Busan#38

Revert "[UPDATE] fes-tour translate (도중)"

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/FestivalController.java
src/main/java/com/frombusan/controller/ReviewController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/static/css/index.css
src/main/resources/templates/member/myJjimList.html
src/main/resources/templates/review/list.html
src/main/resources/templates/review/read.html
src/main/resources/templates/review/reviewList.html

[UPDATE] translate complete

---

src/main/java/com/frombusan/config/WebConfig.java
src/main/java/com/frombusan/controller/CourseController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/course/CourseInfo.html
src/main/resources/templates/course/CourseList.html

[UPDATE] translate almost!

---

src/main/java/com/frombusan/controller/CourseController.java
src/main/java/com/frombusan/model/course/Course.java
src/main/resources/static/css/courseInfo.css
src/main/resources/templates/course/CourseInfo.html

[UPDATE] courseInfo

---

src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/member/myJjimList.html
src/main/resources/templates/member/myReviewList.html

[UPDATE] Jjim translate

---

src/main/java/com/frombusan/controller/CourseController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/course/CourseInfo.html
src/main/resources/templates/fragments/header.html

[UPDATE] courseInfo translate complete

---

src/main/java/com/frombusan/controller/TouristController.java
src/main/resources/static/css/index.css
src/main/resources/templates/main/index.html

[UPDATE] index

---

src/main/resources/static/css/index.css

[UPDATE] index.css

---

src/main/java/com/frombusan/config/WebConfig.java

[UPDATE] WEBCONFIG

---

src/main/java/com/frombusan/controller/ReviewController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/mapper/reviewMapper.xml
src/main/resources/templates/member/myReviewList.html
src/main/resources/templates/review/list.html
src/main/resources/templates/review/read.html
src/main/resources/templates/review/reviewList.html
src/main/resources/templates/review/update.html
src/main/resources/templates/review/write.html

검색 기능에 번역 넣기 존나 힘들ㄷ었음 ㄹㅇ . 누가 나 치킨 사주셈

[ADD] search&translate

---

src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/main/index.html
src/main/resources/templates/review/list.html

[UPDATE] index 번역

---

src/main/java/com/frombusan/model/member/MemberJoinForm.java
src/main/java/com/frombusan/model/member/MemberUpdateForm.java
src/main/resources/static/css/index.css
src/main/resources/static/css/joinForm.css
src/main/resources/static/css/reviewRead.css
src/main/resources/templates/member/joinForm.html

[STYLE] css

---

src/main/java/com/frombusan/controller/MemberController.java
src/main/resources/templates/member/checkMember.html
src/main/resources/templates/member/mypage.html
src/main/resources/templates/member/updateMember.html

[UPDATE] checkMember

---

src/main/java/com/frombusan/controller/FestivalController.java
src/main/java/com/frombusan/controller/TouristController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/java/com/frombusan/service/TouristService.java
src/main/resources/mapper/touristSpotMapper.xml
src/main/resources/templates/tourist/Tourist.html

[UPDATE] tour search

---

src/main/java/com/frombusan/controller/FestivalController.java
src/main/java/com/frombusan/controller/TouristController.java
src/main/resources/templates/festival/FestivalList.html

[UPDATE] fesList complete

---

src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/static/css/Info.css
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/tourist/TouristSpotInfo.html

[UPDATE] trans

---

src/main/java/com/frombusan/controller/TouristController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/festival/FestivalList.html
src/main/resources/templates/main/index.html
src/main/resources/templates/review/list.html
src/main/resources/templates/tourist/Tourist.html
src/main/resources/templates/tourist/TouristSpotInfo.html

번역작업 완료!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[UPDATE] translate finished!

---

src/main/resources/templates/festival/FestivalList.html
src/main/resources/templates/review/list.html
src/main/resources/templates/tourist/Tourist.html

[UPDATE] real last translate update

---

src/main/java/com/frombusan/controller/ReviewController.java
src/main/resources/static/css/myPage.css
src/main/resources/static/css/reviewList.css
src/main/resources/templates/member/checkMember.html
src/main/resources/templates/member/myReviewList.html
src/main/resources/templates/member/mypage.html
src/main/resources/templates/review/list.html
src/main/resources/templates/tourist/Tourist.html

[STYLE] update

---

src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/static/css/findIdForm.css
src/main/resources/static/css/header.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/main/index.html
src/main/resources/templates/member/findId.html

[STYLE] findIdcss생성

---

src/main/java/com/frombusan/controller/ReviewController.java
src/main/resources/static/css/findIdForm.css
src/main/resources/static/css/findPassForm.css
src/main/resources/templates/member/findPassword.html

[UPDATE] findpassform수정

---

src/main/java/com/frombusan/controller/ReviewController.java
src/main/resources/static/css/reviewList.css
src/main/resources/templates/member/myReviewList.html

[STYLE] reviewList

---

src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/static/css/Info.css
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/tourist/TouristSpotInfo.html

[UPDATE] map-translate

---

src/main/resources/static/css/Info.css
src/main/resources/static/css/reviewRead.css

[STYLE] buttonUpdate

---

src/main/resources/static/css/changePassForm.css
src/main/resources/static/css/updateMember.css
src/main/resources/templates/member/changePassword.html
src/main/resources/templates/member/updateMember.html

updateMember.css추가 changePass.css수정

[STYLE] updateMember.css추가 및 css수정

---

src/main/resources/static/css/Info.css
src/main/resources/static/css/myJjimList.css
src/main/resources/templates/festival/FestivalInfo.html
src/main/resources/templates/main/index.html
src/main/resources/templates/tourist/TouristSpotInfo.html

[STYLE] info.css Jjimlist.css 변경

---

src/main/java/com/frombusan/service/ReviewService.java
src/main/resources/mapper/festivalMapper.xml
src/main/resources/mapper/touristSpotMapper.xml

[UPDATE] index좋아요수정

---

src/main/resources/static/css/reviewList.css
src/main/resources/templates/review/list.html

[STYLE] list.css

---

src/main/java/com/frombusan/controller/ReviewController.java
src/main/java/com/frombusan/controller/TranslatorController.java
src/main/resources/templates/review/write.html

[UPDATE] WRITE.html translate
